### PR TITLE
fixes #4 update grammar to the latest spec

### LINKED ISSUE #4: update grammar to the latest spec
see https://github.com/highlightjs/highlight.js/issues/3008

### PR DESCRIPTION
**Pull request by marcellourbani**
@larshp 
This fits the bill of adjusting to the new format, but the output isn't great:
image
i.e. CLASS is not a keyword, comments are not dealt properly,...

To fix that I'll need to actually  fix the grammar, possibly based on Marc's file above.
But I think it deserves its own PR

### CODE REVIEW

**Comment by joshgoebel** [comment]
Are you sure the grammar is loaded properly?  It seems to have support for comments...

**Comment by larshp** [comment]
heh, I dont exactly remember how things work 😄

@marcellourbani what triggered the above output? highlight js has some language auto-detection, did it detect a different language?

we need to setup some kind of automatic testing #3, some of the other repos in https://github.com/highlightjs probably got something we can borrow

**Comment by marcellourbani** [comment]
I'm pretty confident: if I change the keywords the highlighting changes.
I think the begin condition is problematic, as contains a ^ (which is correct, * at the beginning of the line starts a comment, in other positions is either a multiplication or a syntax error)

```javascript
    	{
    		className: 'comment',
    		begin: '^[*]',
    		relevance: 0,
    		end: '\n'
    	}
```
It does need fixing, just not sure the fix belongs to this PR

**Comment by larshp** [comment]
the new `dist/abap.min.js` file, its a generated file? in that case we need to update the readme how to generate it and possibly add scripts in `package.json`

**Comment by marcellourbani** [comment]
That's done by the main package, I will add a note about it.
Don't like the process one bit, but will document what it is

**Comment by marcellourbani** [comment]
@joshgoebel 
Ok, the comments work fine if the text is not indented.
image
grammar still needs fixing for the missing keywords like CLASS and ENDCLASS

**Comment by joshgoebel** [comment]
> Ok, the comments work fine if the text is not indented.

Yeah, the `^[*]` rule would need to be updated to allow for potential whitespace... :-)

> Don't like the process one bit, but will document what it is

You're welcome to generate `dist` in a different fashion if you think it'd be simpler... but there are other (testing/security) benefits to the current recommended setup as well.

**Comment by marcellourbani** [comment]
@larshp I added the build instructions in README
@joshgoebel what I would like is a build command to run in my package.json
From what I understand of the tooling, as of today this would require:

- clone the main repo
- copy this in its extra folder
- download modules
- build
- copy the dist folder
- cleanup

Which is way more complex than what I feel like doing for this
I'm ok updating manually as we barely ever touch it

**Comment by larshp** [comment]
@marcellourbani thanks, merging

**Comment by joshgoebel** [comment]
> Which is way more complex than what I feel like doing for this
> I'm ok updating manually as we barely ever touch it

Yeah, it could be simpler, but after it's setup it's not much effort at all.  Also, I've always started with the assumption that grammar authors are *already building us* - you need to in order to debug and test your grammar with the developer tools we provide (which are pretty helpful).  Is that a faulty assumption?

> what I would like is a build command to run in my package.json

_Once you had the structure setup once_ I'd think a bash script that simply `cd ../.. && build && cd extra/your_repo` would suffice, no?  I'm not saying that's perfect, but wouldn't that mostly work?

**Comment by marcellourbani** [comment]
@joshgoebel 
Ok. Don't really like it but see no reason to make a fuss

**Pull request merged**
