### PR TITLE
Updated list of ABAP words

### PR DESCRIPTION
**Pull request by SacrumDeus**
In reference to #10, I'd like to contribute this pull request

What have I done:

- Addes some key words
- Fixed some errors at the end of the line (a space was missing which causes the no-identification of some words (such as `CA`)
- Added boolean value `abap_undefined` (which is a boolean value in SAP ABAP)

Built minified version with Node@20.4.0

### CODE REVIEW

**Comment by larshp** [comment]
`dist/abap.min.js` does look a bit different than before, if I publish a version today, will you be around to fix issues if any shows up?

**Comment by SacrumDeus** [comment]
yes, I will be around

I used the process as you described in `README.md` to build the `dist/abap.min.js`-file

**Comment by larshp** [comment]
yea.. other things might have changed since last publish

**Comment by larshp** [comment]
0.3.0 published

**Pull request merged**
